field: f2e5c428-680b-4d82-810b-a0d5e1ead17f # Footer Menu
fieldLayouts:
  333c6f24-f2ac-40bd-a60b-54f23d008326:
    tabs:
      -
        elements:
          -
            fieldUid: 75d9dd9c-34cd-4041-8eaa-6de7733332b6 # Custom Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c3ab0099-2bd0-4fb3-9f99-0b7ef05a796d # Custom URL
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  75d9dd9c-34cd-4041-8eaa-6de7733332b6: # Custom Title
    columnSuffix: ziefmbwr
    contentColumnType: text
    fieldGroup: null
    handle: customTitle
    instructions: ''
    name: 'Custom Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c3ab0099-2bd0-4fb3-9f99-0b7ef05a796d: # Custom URL
    columnSuffix: xqajpabd
    contentColumnType: string(255)
    fieldGroup: null
    handle: customUrl
    instructions: ''
    name: 'Custom URL'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
        - tel
        - email
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: custom
name: Custom
sortOrder: 2
