fieldLayouts:
  c362e989-1d89-4904-b246-aa142e0d248c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1242584a-c842-4598-bf15-dfc1f53dec45
            warning: null
            width: 100
          -
            fieldUid: 51c27d0d-e6ac-45ab-92e4-4e2eb69766ff # Banner
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d6bad5f-b304-4b7d-885c-62d4a1fa21a3
            warning: null
            width: 100
        name: Content
        uid: 62ba83da-334c-46ee-9500-0af8ffed3d4b
      -
        elements:
          -
            fieldUid: db74e3e8-29b2-475d-bbae-ff18672720f1 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8946303e-f193-430f-88d1-b57f21f7be5b
            warning: null
            width: 100
        name: SEO
        uid: e94e1904-d810-4289-b393-f6ba7fc65562
handle: contact
hasTitleField: true
name: Contact
section: 7043c508-fdf8-4bf1-a9d9-cdfa67ca6cc2 # Contact
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
