fieldLayouts:
  4c158bd5-b386-4482-b8c7-d6a51c6d64fb:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c1807e1b-ca51-46b8-a1bd-df70a2557eea
            warning: null
            width: 100
          -
            fieldUid: 2b5c3999-f111-4535-8ecd-a81e95483d94 # Blog Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2ee051a-7c82-44b3-a125-9bfc9b78feb7
            warning: null
            width: 100
        name: Content
        uid: d0e34251-965c-4e68-adb6-6e3821aee376
      -
        elements:
          -
            fieldUid: db74e3e8-29b2-475d-bbae-ff18672720f1 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b835e2e-d029-4932-b2e3-547bd4712d92
            warning: null
            width: 100
        name: SEO
        uid: d9d938d9-f19a-400b-ad0f-79ef99f17837
handle: default
hasTitleField: true
name: Default
section: 1c008561-0013-4b4d-b04a-f51a038c5a20 # Blog - Items
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
