fieldLayouts:
  1a58eba3-7362-47c6-891d-4b0129387ba9:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 938c51e4-95a8-4a6b-b456-1a7a89ef0b52
            warning: null
            width: 100
          -
            fieldUid: 51c27d0d-e6ac-45ab-92e4-4e2eb69766ff # Banner
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10e91c0b-6dd0-4a41-9cbd-3db8cf27657d
            warning: null
            width: 100
        name: Content
        uid: b538b700-81e4-42ac-a565-e45a9d3bf203
      -
        elements:
          -
            fieldUid: db74e3e8-29b2-475d-bbae-ff18672720f1 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5867e3f-564c-40fd-bc54-208093a35c6d
            warning: null
            width: 100
        name: SEO
        uid: aefe0933-1f7e-4848-a8ee-20c1a264eeae
handle: pages
hasTitleField: true
name: Pages
section: 1fa133fd-47b8-4acc-857d-b9677a729349 # Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
