defaultPlacement: end
fieldLayouts:
  f4c858c9-307a-4cff-9f34-412de984cc39:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 820a6a9e-fc03-4e5a-baea-a50970939e2c
            warning: null
            width: 100
          -
            fieldUid: 5efbbd6a-2d8b-4ef0-b03a-1bf53718f687 # Blog Category Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2c5067c-76c1-4fee-9b0a-58c8627b97c5
            warning: null
            width: 100
        name: Content
        uid: 83ca09db-3144-47ae-9db0-c3ed02d08e2a
handle: blogCategories
name: 'Blog Categories'
siteSettings:
  4d8ac26f-0eed-4e84-8f0f-fb59450142e3: # English
    hasUrls: false
    template: null
    uriFormat: null
  f5399107-84c7-4af5-8764-8c333d1b9ebc: # Dutch
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 4641dbd1-76ee-44b0-ab32-bb5f902609b0
