fieldLayouts:
  ed0618ae-16b1-40e7-b501-f1c7feb9e0a4:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ad022d95-31c5-4f14-a660-8167e0ff4755
            warning: null
            width: 100
        name: Content
        uid: bc8d02a4-f2b7-4351-bdeb-899a174d267d
fs: main
handle: main
name: Main
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: _transforms
