columnSuffix: null
contentColumnType: string
fieldGroup: 6e6e5ab5-ec46-433d-80af-42840709af85 # Common
handle: banner
instructions: null
name: Banner
searchable: false
settings:
  contentTable: '{{%matrixcontent_banner}}'
  maxBlocks: 1
  minBlocks: 1
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
