columnSuffix: null
contentColumnType: string
fieldGroup: 7e985e9f-e680-483b-8355-eaa0ffe93374 # Blog
handle: blogCategory
instructions: null
name: 'Blog Category'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:541a135e-c132-4a7f-b2ef-9869b60caba3' # Blog Categories
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
