fieldLayouts:
  7c007c3a-2be6-49f4-b030-95c50b49314a:
    tabs:
      -
        elements:
          -
            fieldUid: ec412734-268e-44c6-a6f7-f2e534090a2a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: f2e5c428-680b-4d82-810b-a0d5e1ead17f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Menu
        sortOrder: 1
handle: navigation
name: Navigation
sortOrder: 1
