defaultPlacement: end
enableVersioning: true
handle: blog
name: Blog
propagationMethod: all
siteSettings:
  4d8ac26f-0eed-4e84-8f0f-fb59450142e3: # English
    enabledByDefault: true
    hasUrls: true
    template: _blog/_entry
    uriFormat: 'blog/{slug}'
  f5399107-84c7-4af5-8764-8c333d1b9ebc: # Dutch
    enabledByDefault: true
    hasUrls: true
    template: _blog/_entry
    uriFormat: 'blog/{slug}'
type: channel
