defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
propagationMethod: all
siteSettings:
  4d8ac26f-0eed-4e84-8f0f-fb59450142e3: # $SITE_NAME_EN
    enabledByDefault: true
    hasUrls: true
    template: _pages
    uriFormat: '{slug}'
  f5399107-84c7-4af5-8764-8c333d1b9ebc: # $SITE_NAME_NL
    enabledByDefault: true
    hasUrls: true
    template: _pages
    uriFormat: '{slug}'
type: channel
